steps:
  - id: 'terraform fmt check'
    dir: 'src'
    name: 'hashicorp/terraform'
    env:
      - 'TF_VAR_project=$PROJECT_ID'
    args: ['fmt', '-check', '-diff']

  - id: 'terraform init'
    dir: 'infra_unittesting/src'
    env:
      - 'TF_VAR_project=$PROJECT_ID'
    name: 'hashicorp/terraform'
    args: ['init']

  - id: 'terraform plan'
    dir: 'infra_unittesting/src'
    name: 'hashicorp/terraform'
    env:
      - 'TF_VAR_project=$PROJECT_ID'
    args: ['plan']

  - id: 'terraform apply'
    dir: 'infra_unittesting/src'
    name: 'hashicorp/terraform'
    env:
      - 'TF_VAR_project=$PROJECT_ID'      
    args: ['apply', '-auto-approve']


  - id: 'testing environment configuration'
    dir: 'infra_unittesting/test'
    name: 'us-central1-docker.pkg.dev/$PROJECT_ID/testing/cinc-gcp'
    env:
      - 'TF_VAR_project=$PROJECT_ID'
    args: ['exec', '.']
    
timeout: '3600s'
