steps:
  - id: 'testing environment configuration'
    dir: 'test'
    name: 'us-central1-docker.pkg.dev/$PROJECT_ID/testing/cinc-gcp'
    env:
      - TF_VAR_project: $PROJECT_ID
    args: ['exec', '.']
